INSERT INTO `book` (`book_id`, `author`, `publication_year`, `publisher`, `book_name`, `term`, `edition`, `category`) VALUES
(3070, 'Roger Pressman', 1986, 'McGraw Hill Education', 'Software Engineering', '1', '5th', 'Memoir'),
(3071, 'Roger Pressman', 1986, 'McGraw Hill Education', 'Software Engineering', '1', '7th', 'CSE'),
(3072, 'Roger Pressman', 1989, 'McGraw Hill Education', 'Software Engineering', '1', '8th', 'CSE'),
(3073, 'Roger Pressman', 1989, 'McGraw Hill Education', 'Software Engineering', '1', '8th', 'CSE'),
(3074, 'Roger Pressman', 1990, 'McGraw Hill Education', 'Software Engineering', '1', '9th', 'CSE'),
(3075, 'Roger Pressman', 1990, 'McGraw Hill Education', 'Software Engineering', '1', '9th', 'CSE'),
(3076, 'Roger Pressman', 1990, 'McGraw Hill Education', 'Software Engineering', '1', '9th', 'CSE'),
(3077, 'Roger Pressman', 1990, 'McGraw Hill Education', 'Software Engineering', '1', '9th', 'CSE'),
(4060, 'Sanjay Sharma', 1997, 'Karitia & Sons', 'Analog Communication', '1', '1st', 'ECE'),
(4061, 'Sanjay Sharma', 1997, 'Karitia & Sons', 'Analog Communication', '1', '1st', 'ECE'),
(4062, 'Sanjay Sharma', 1997, 'Karitia & Sons', 'Analog Communication', '1', '1st', 'ECE'),
(4063, 'Sanjay Sharma', 2000, 'Karitia & Sons', 'Analog Communication', '1', '2nd', 'ECE'),
(4064, 'Sanjay Sharma', 2000, 'Karitia & Sons', 'Analog Communication', '1', '2nd', 'ECE'),
(4065, 'Sanjay Sharma', 2000, 'Karitia & Sons', 'Analog Communication', '1', '2nd', 'ECE'),
(4066, 'Sanjay Sharma', 2000, 'Karitia & Sons', 'Analog Communication', '1', '2nd', 'ECE'),
(4067, 'Sanjay Sharma', 2000, 'Karitia & Sons', 'Analog Communication', '1', '2nd', 'ECE'),
(5050, 'Sheply L. Ross', 1994, 'John Willey & Sons', 'Differential Equations', '1', '3rd', 'MATH'),
(5051, 'Sheply L. Ross', 1994, 'John Willey & Sons', 'Differential Equations', '1', '3rd', 'MATH'),
(5052, 'Sheply L. Ross', 1994, 'John Willey & Sons', 'Differential Equations', '1', '3rd', 'MATH'),
(5053, 'Sheply L. Ross', 1994, 'John Willey & Sons', 'Differential Equations', '1', '2nd', 'MATH'),
(5054, 'Sheply L. Ross', 1994, 'John Willey & Sons', 'Differential Equations', '1', '2nd', 'MATH'),
(5055, 'Sheply L. Ross', 1994, 'John Willey & Sons', 'Differential Equations', '1', '2nd', 'MATH'),
(5056, 'Sheply L. Ross', 1994, 'John Willey & Sons', 'Differential Equations', '1', '2nd', 'MATH'),
(5057, 'Sheply L. Ross', 1994, 'John Willey & Sons', 'Differential Equations', '1', '2nd', 'MATH'),
(5058, 'Sheply L. Ross', 1994, 'John Willey & Sons', 'Differential Equations', '1', '2nd', 'MATH'),
(6060, 'M. Rafiquzzaman', 1990, 'Prentice Hall of India', 'Microprocessors Theory and Aplications', '1', '4th', 'CSE'),
(6061, 'M. Rafiquzzaman', 1990, 'Prentice Hall of India', 'Microprocessors Theory and Aplications', '1', '4th', 'CSE'),
(6062, 'M. Rafiquzzaman', 1990, 'Prentice Hall of India', 'Microprocessors Theory and Aplications', '1', '4th', 'CSE'),
(6063, 'M. Rafiquzzaman', 1990, 'Prentice Hall of India', 'Microprocessors Theory and Aplications', '1', '3rd', 'CSE'),
(6064, 'M. Rafiquzzaman', 1990, 'Prentice Hall of India', 'Microprocessors Theory and Aplications', '1', '3rd', 'CSE'),
(6065, 'M. Rafiquzzaman', 1990, 'Prentice Hall of India', 'Microprocessors Theory and Aplications', '1', '3rd', 'CSE'),
(6066, 'M. Rafiquzzaman', 1990, 'Prentice Hall of India', 'Microprocessors Theory and Aplications', '1', '3rd', 'CSE'),
(6067, 'M. Rafiquzzaman', 1990, 'Prentice Hall of India', 'Microprocessors Theory and Aplications', '1', '3rd', 'CSE');
